dist: trusty
sudo: required
language: bash
env:
  - PACKER_VARIABLES: packer/variables.json.example
    TFLINT_VERSION: v0.17.0
before_install:
# install all dependencies
- sudo apt-get install unzip
- curl -O https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
- sudo unzip terraform_0.12.28_linux_amd64.zip -d /usr/local/bin
- terraform -v
- sudo pip install ansible ansible-lint
- curl https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | sudo bash
# packer validate
- set -e
- |
  for cur_file in $(find packer/ -name '*.json' -not -path "packer/backup/*")
  do
    echo $cur_file =================
    packer validate -var-file $PACKER_VARIABLES $cur_file
  done
# terraform validate
- |
  for terra_file in $(find  terraform/ -name 'main.tf' -not '(' -path '*/.*' -or -path '*backup*' ')' -exec dirname {} \; | uniq)
  do
    echo $terra_file =================
    (cd $terra_file && terraform init -backend=false > /dev/null && echo Validating && terraform validate && echo Running linter... && tflint && echo Successfull!)
  done
# ansible validate
- |
  for ansible_playbook in $(find ansible/playbooks -name '*.yml' -or -name '*.yaml')
  do
    echo $ansible_playbook =================
    ansible-lint -x 403 $ansible_playbook
  done
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh |
  bash
notifications:
  slack:
    rooms:
      secure: x5fNTkQQ8r9dfdyje/v8vjbdYcW/nd/O1ICbTag1Vnfcea6wQLKD/+0gPtvv9Op68pTCOT8d7Mx1JV+OUiq+cDIZ/j9EO0DaymNk9TLR8EjUKuKWHYmyms8cO3XE5wTFH/xWbIWA53Ck6+19RoRWTa68gBXV6Q/KGlpCX2xv4DlbsxGVI7u3fD8Dj/3rpdzNDHRId7pVs3BW2AwageUnfW+eFXUujFkWPFeV7K2PjG0Rc6i8dClsWy4Bi68pgrBm+RNefKWvIey3HY636M2PXzwuRuZ5pDj83V/sLc3ghkKoHJYI1IUtLRaahCCpCfmDvLLyeOo2CwGiT5obPSVB6dBGN9SVbu1Sbo6fP9ly5yZ5/Wp7BoYPYRe550cWCpNLIlTOZdsiZIVON5eGte0Psm6tTAy/q7qqtKlLrmxwW9HEK2jzcYEw2zYqp6vlUZR++Y48HvGDGx9oBVyWtQkotJawnBiPkrbUBRyBs4Cm4vqfarqOCwAsqiXvjMCORY0hrnGNuLd/KIOfz/fmPxpse0SLu0kWtFAwO6SaSRjBMJPzWSq+qEcrs8YrXJVZUDuseBQiyIPktIHM366I/v20zMX/X3ncm99THuZmpilMi/JPw3BCq/veC5AGGDGb2wlrAqOBlN6+zNiTVwnZOhui1ta0PijTKl5VfeLh9BqbTj8=
